blog/urls.py
from django.urls import path

from . import views
from blog.apps import BlogConfig



app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

blogs/urls.py
from django.urls import path

from . import views
from blogs.apps import BlogConfig



app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, email_verefication

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', RegisterView.as_view(template_name='register.html'), name='register'),
    path('email-confirm/<str:token>/', email_verefication, name='email_confirm')
]

blogs/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок статьи')
    content = models.TextField(verbose_name='Содержание статьи')
    preview = models.ImageField(upload_to='images/', verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(null=True)
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-created_at']

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Post



class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 3  # Количество постов на странице
    ordering = ['-created_at']  # Сортировка постов по дате создания в обратном порядке

    def get_queryset(self):  # фильтрация постов по опубликованным
        return Post.objects.filter(published=True)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):  # увеличение счетчика просмотров
        post = super().get_object()
        post.views_count += 1
        post.save()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form): # изменение флага состояния при сохранении
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)



class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:post_detail') # используем параметр success_url

    def get_success_url(self):
        post = self.get_object()
        return reverse_lazy('blog:post_detail', kwargs={'pk': post.pk})

    def form_valid(self, form):
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete_confirm.html'
    success_url = reverse_lazy('blog:home')
    context_object_name = 'post'

blogs/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blogs.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin



class PostListView(ListView):
    model = Post
    template_name = 'blogs/post_list.html'
    context_object_name = 'posts'
    paginate_by = 3  # Количество постов на странице
    ordering = ['-created_at']  # Сортировка постов по дате создания в обратном порядке

    def get_queryset(self):  # фильтрация постов по опубликованным
        return Post.objects.filter(published=True)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blogs/post_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):  # увеличение счетчика просмотров
        post = super().get_object()
        post.views_count += 1
        post.save()
        return post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blogs/post_form.html'
    success_url = reverse_lazy('blogs:home')

    def form_valid(self, form): # изменение флага состояния при сохранении
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)



class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', 'preview']
    template_name = 'blogs/post_form.html'
    success_url = reverse_lazy('blogs:post_detail') # используем параметр success_url

    def get_success_url(self):
        post = self.get_object()
        return reverse_lazy('blogs:post_detail', kwargs={'pk': post.pk})

    def form_valid(self, form):
        post = form.save(commit=True)
        post.published = True
        post.save()
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blogs/post_delete_confirm.html'
    success_url = reverse_lazy('blogs:home')
    context_object_name = 'post'

blogs/templates/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>О нас</h4>
          <p class="text-body-secondary">Мы магазин с самыми честными ценами во всём мире, наша стратегия крайне проста, мы скупаем у нигеров, происхождение товара нас не интересует, в итоге вы получете оригиналы и бренды прям с полок самых центровых бутиков США. <br>У нас пожизненная гарантия на все товары, только пожалуйтесь и мы тут же пришлём к вам наших нигеров.<br> Ещё ни кто не жаловался, чистейшая репутация, гарантия и самые низкие цены !!!</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          {% if user.is_authenticated %}
          <p>Добро пожаловать, {{ user.first_name }}!</p>
          {% else %}
          <p>Добро пожаловать на наш сайт!</p>
          {% endif %}
          <ul class="list-unstyled">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-link nav-link">Выйти
                      </button>
                  </form>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
              </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong></strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>