blog/urls.py
from django.urls import path

from . import views
from blog.apps import BlogConfig



app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('post_detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('add_post/', views.PostCreateView.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    ]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
# from . import views
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ContactTemplateView,
    ProductDeleteView,
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    CategoryProductListView,
)
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('', ProductListView.as_view(), name="product_list"),
    path('product/<int:pk>/',cache_page(60 * 15)(ProductDetailView.as_view()), name="product_detail"),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('edit_product/<int:pk>', ProductUpdateView.as_view(), name='edit_product'),

    path('product/<int:catalog_product_id>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('catalog/<int:owner_id>/', ProductListView.as_view(), name='user_catalog'),

    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('add_category/', CategoryCreateView.as_view(), name='add_category'),
    path('category/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),

    path('category/<int:category_id>/products/', CategoryProductListView.as_view(), name='category_products'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import CustomUser

PUBLICATION_STATUS_CHOICES = [
    ('unpublished', 'Не опубликован'),
    ('draft', 'Черновик'),
    ('pending_review', 'Ожидает проверки'),
    ('published', 'Опубликован'),
]


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        permissions = [
            ("can_change_category", "Can change category"),
            ("can_delete_category", "Can delete category"),
        ]

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to="catalog/product_images", null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="catalog")
    purchase_price = models.FloatField(verbose_name="Цена товара", help_text="Введите цену товара")
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    publication_status = models.CharField(max_length=20, choices=PUBLICATION_STATUS_CHOICES, default='unpublished')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Владелец', help_text='Укажите владельца')

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]

        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
            ("can_delete_product", "Can delete product"),
        ]

    def save(self, *args, **kwargs):
        self.full_clean()  # Вызывает все методы валидации модели
        super().save(*args, **kwargs)

catalog/forms.py
from django import forms
from django.forms import ModelForm, BooleanField
from django.core.exceptions import ValidationError
from django.conf import settings

from catalog.models import Product
from .models import Category


def validate_forbidden_words(value):
    forbidden_words = getattr(settings, "FORBIDDEN_WORDS", [])
    value_lower = value.lower()
    for word in forbidden_words:
        if word in value_lower:
            raise ValidationError(f'Использование слова "{word}" запрещено.')


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

class ProductModeratorForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['created_at', 'updated_at', "owner"]

    def clean_purchase_price(self):
        price = self.cleaned_data.get("purchase_price")
        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной")
        return price

    def clean_name(self):
        name = self.cleaned_data.get("name")
        validate_forbidden_words(name)
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        validate_forbidden_words(description)
        return description



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "image", "category", "purchase_price"]

    def clean_purchase_price(self):
        price = self.cleaned_data.get("purchase_price")
        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной")
        return price

    def clean_name(self):
        name = self.cleaned_data.get("name")
        validate_forbidden_words(name)
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        validate_forbidden_words(description)
        return description

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({"class": "form-check-input"})
            else:
                field.widget.attrs.update({"class": "form-control"})




class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description')

catalog/views.py
import logger
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
    DeleteView,
    View,
)


from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from .forms import ProductForm, ProductModeratorForm, CategoryForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.utils.decorators import method_decorator
from django.core.cache import cache
from .models import Category, Product

from .services import get_products_by_category


class CategoryListView(ListView):
    """Представляет категории для списка категорий """
    model = Category
    template_name = 'catalog/category_list.html'
    context_object_name = 'categories'


class CategoryProductListView(ListView):
    """Представляет продукты той категории в которую провалился из списка категории """
    model = Product
    template_name = 'catalog/category_product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        category_id = self.kwargs.get('category_id')
        return get_products_by_category(category_id)



class CategoryDetailView(DetailView):
    model = Category
    template_name = 'catalog/category_detail.html'
    context_object_name = 'category'

class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'catalog/category_form.html'
    success_url = '/catalog/'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'catalog/category_form.html'
    context_object_name = 'object'
    success_url = '/catalog/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение категории'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'].owner = self.request.user
        return kwargs

class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'catalog/category_delete.html'
    success_url = '/catalog/'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().owner != request.user:
            return redirect('category_list')
        return super().dispatch(request, *args, **kwargs)


class HomeView(TemplateView):
    template_name = "home.html"


class ContactTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        return context


class ProductListView(ListView):
    model = Product
    template_name = "catalog/product_list.html"
    context_object_name = "product"

    # def get_queryset(self):
    #     return Product.objects.filter(published=True)


class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_create.html"
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        product = form.save(commit=False)  # Создаем продукт, но не сохраняем в БД
        product.published = True  # Устанавливаем статус опубликованного
        user = self.request.user  # Получаем текущего пользователя
        product.owner = user  # Привязываем пользователя как владельца
        product.save()  # Сохраняем продукт в БД
        return super().form_valid(form)  # Вызываем родительский метод

class ProductUpdateView(LoginRequiredMixin,UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_update.html"
    # success_url = reverse_lazy("catalog:product_detail")

    def get_success_url(self):
        try:
            return reverse('catalog:product_detail', args=[self.object.pk])
        except Exception as e:
            # Логирование ошибки
            logger.error(f"Error in get_success_url:{str(e)}")
            return reverse('catalog:products_list')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('catalog.can_unpublish_product'):
            return ProductModeratorForm

        return ProductForm



class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_delete_confirm.html"
    pk_url_kwarg = 'catalog_product_id'

    def post(self, request, catalog_product_id):
        product = get_object_or_404(Product, id=catalog_product_id)
        if not request.user.has_perm('catalog.can_delete_product'):
            return HttpResponseForbidden("У вас нет прав для удаления продукта.")
        product.delete()
        return redirect('catalog:product_list')

    # permission_classes = 'catalog.can_delete_product'
    # # success_url = reverse_lazy("catalog:product_detail")
    #
    # def get_success_url(self):
    #     return reverse_lazy("catalog:product_list")



class BaseTemplateView(TemplateView):
    template_name = "base.html"


index_view = BaseTemplateView.as_view()

catalog/templates/catalog/category_create.html
{% extends 'catalog/base.html' %}

{% block title %}{% if object %}Изменение{% else %}Добавление{% endif %} категории{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% if object %}Изменение{% else %}Добавление{% endif %} категории</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% if object %}Обновить{% else %}Добавить{% endif %}</button>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/category_delete_confirm.html
{% extends 'catalog/base.html' %}

{% block title %}Удаление категории{% endblock %}

{% block content %}
    <div class="container">
        <h1>Удаление категории</h1>
        <p>Вы уверены, что хотите удалить эту категорию?</p>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ category.id }}">
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'category_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}

{% block title %}Подробности категории{% endblock %}

{% block content %}
    <div class="container">
        <h1>Подробности категории</h1>
        <a href="{% url 'category_list' %}" class="btn btn-primary mb-3">Вернуться к списку</a>

        <h2>Название: {{ category.name }}</h2>
        <p>Описание: {{ category.description|truncatewords:50 }}</p>

        {% if user.is_authenticated %}
        {% if perms.catalog.change_category or category.owner == user %}
        <a href="{% url 'category_update' category.id %}" class="btn btn-secondary">Изменить</a>
        {% endif %}
        {% endif %}
    </div>
{% endblock %}

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block title %}{% if object %}Изменение{% else %}Добавление{% endif %} категории{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% if object %}Изменение{% else %}Добавление{% endif %} категории</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% if object %}Обновить{% else %}Добавить{% endif %}</button>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block title %}Список категорий{% endblock %}

{% block content %}
    <div class="container">
        <h1>Список категорий</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                    <tr>
                        <td>{{ category.id }}</td>
                        <td><a href="{% url 'catalog:category_products' category.id %}">{{ category.name }}</a></td>
                        <td>{{ category.description|truncatewords:50 }}</td>
                        <td>
                            {% if user.is_authenticated %}
                                {% if perms.catalog.change_category %}
                                    <a href="{% url 'catalog:category_update' category.id %}" class="btn btn-sm btn-warning">Изменить</a>
                                    {% if perms.catalog.delete_category %}
                                        <a href="{% url 'catalog:category_delete' category.id %}" class="btn btn-sm btn-danger">Удалить</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

catalog/templates/catalog/category_product_list.html
{% extends 'catalog/base.html' %}

{% block title %}Список продуктов в категории {{ category.name }}{% endblock %}

{% block content %}
  <div class="container">
      <h1>Продукты в категории </h1>

      {% if products %}
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
              {% for product in products %}
              <div class="col">
                  <div class="card shadow-sm">
                      <div class="card-body">
                          <h5>{{product.name}}</h5>
                          <h6>Категория: {{product.category}}</h6>
                          <p>Цена: {{product.purchase_price}} ₽</p>

                      </div>
                  </div>
              </div>
              {% endfor %}
          </div>
      {% else %}
          <p>В этой категории нет продуктов.</p>
      {% endif %}
  </div>
{% endblock %}

catalog/templates/catalog/category_update.html
{% extends 'catalog/base.html' %}

{% block title %}{% if object %}Изменение{% else %}Добавление{% endif %} категории{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% if object %}Изменение{% else %}Добавление{% endif %} категории</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% if object %}Обновить{% else %}Добавить{% endif %}</button>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{%block content%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Другие способы связаться с вами" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
{%endblock%}

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}


{% block title %}Товарная форма{% endblock %}

    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1 class="display-4 text-center">Мерчандайзинг наших товаров</h1>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {{ form.as_p }}

                            {% if user.is_authenticated and perms.catalog.add_product%}
                                <button type="submit" class="btn btn-primary">☕️ Сохранить</button>
                            {% endif %}
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}

catalog/templates/catalog/product_delete_confirm.html
{% extends 'catalog/base.html' %}


{% block title %}Товарная форма{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Мерчандайзинг наших товаров</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                {% if user.is_authenticated %}
                    {% if perms.catalog.delete_product or product.owner == user %}
                        <button type="submit" class="btn btn-danger">🍂 Подтвердите удаление 🍂</button>
                    {% endif %}
                {% endif %}

                <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">🍂 Отмена 🍂</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
<!--# этот тег указывает, что используемый шаблон-->
{%load my_tags%}
{%block content%}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-3">
<!--        Это место для цикла for ниже endfor его закрывающий тег-->
        <div class="col">
          <div class="card shadow-sm">
            <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Вернуться назад</a>

            {% if user.is_authenticated%}
              {% if perms.catalog.change_product or product.owner == user %}
                <a href="{% url 'catalog:edit_product' product.pk %}" class="btn btn-secondary">Редактировать</a>
                {% if perms.catalog.delete_product %}
                  {% if product.owner == user %}
                    <a href="{% url 'catalog:delete_product' product.pk %}" class="btn btn-danger">Удалить</a>
                  {% endif %}
                {% endif %}
              {% endif %}
            {% endif %}

            <img src="{{product.image | media_filter}}">
<!--            product.image продукт берётся из views а имэйдж из Product на который ссылается product в views-->
            <div class="card-body">
              <p class="card-text">{{product.name}}</p>
              <p class="card-text"> Категория: {{product.category}}</p>
              <p class="card-text">{{product.description}}</p>
              <h1> <p class="card-text">Цена: {{product.purchase_price}}₽</p> </h1>
              <div class="d-flex justify-content-between align-items-center">
                <div class="owner-info">
                   <h3 class="fw-light"> Закон позволяет стихийные сделки, <br>
                     так давай сделаем это ! <br>
                     По вопросам покупки или бартера на дочь <br>
                     или отары овец пищи по адресу : <br>
                     {{ product.owner.email }} <br>
                     Чужие кони, жёны и фамильное оружие в оплату не предлагать !
                     БАН на три дня !
                   </h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{%endblock%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}


{% block title %}Товарная форма{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Товарная форма</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
<!--# этот тег указывает, что используемый шаблон-->
{%load my_tags%}
{%block content%}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for product in object_list%}
<!--        Это тег цикла ниже endfor его закрывающий тег-->
          <div class="owner-info">
                  Владелец: {{ product.owner.username }} ({{ product.owner.email }})
            <div class="col">
              <div class="card shadow-sm">
                <img src="{{product.image | media_filter}}">
    <!--            product.image продукт берётся из views а имэйдж из Product на который ссылается product в views-->
                <div class="card-body">
                  <p class="card-text">{{product.name}}</p>
                  <p class="card-text">{{product.description | truncatechars:100 }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-secondary my-2">Подробнее</a>
    <!--  Кнопка/ссылка на продукт с prymary key, открывает распределённые по странице элементы определяя по ключу из базы данных-->
                      <a href="#" class="btn btn-primary my-2">Купить</a>
                    </div>
                    <small class="text-body-secondary">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {%endfor%}
      </div>
    </div>
  </div>
{%endblock%}

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}


{% block title %}Товарная форма{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 text-center">Мерчандайзинг наших товаров</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                {% if user.is_authenticated %}
                    {% if product.owner == user %}
                        <p>Пользователь: {{ user.username }}</p>
                        <p>Владелец товара: {{ product.owner }}</p>
                        <p>Права доступа: {{ perms.catalog.can_change_product }}</p>
                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                    {% else %}
                        <p>Нет прав на изменение товара</p>
                    {% endif %}
                {% else %}
                    <p>Пользователь не авторизован</p>
                {% endif %}

                <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}